# NumPy Practical Test

### Q1. Create a 1D NumPy array of numbers from 0 to 9.

In [20]:
import numpy as np

In [45]:
arr1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Q2. Create a 2D array of shape (3, 3) with all elements as 1.

In [46]:
arr2D = np.array([[1, 1, 1],[1, 1, 1],[1, 1, 1]])
arr2D

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Q3. Generate a NumPy array of 15 random integers between 10 and 50.

In [47]:
random_arr = np.random.randint(10, 50, 15)
random_arr

array([29, 27, 23, 34, 45, 23, 11, 29, 48, 38, 39, 20, 41, 11, 24])

### Q4. Create an array of 5 evenly spaced numbers between 0 and 1 (inclusive).

In [50]:
arr_space = np.linspace(0, 1, 5)
arr_space

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Q5. Create a 4x4 identity matrix using NumPy.

In [42]:
identity_matrix = pd.identity(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Q6. Create an array from the list [10, 20, 30, 40] and change the data type to float.

In [49]:
arr_list = np.array([10,20,30,40], dtype = float)
arr_list

array([10., 20., 30., 40.])

### Q7. Create a 3x3 array with values from 1 to 9, then extract the second column.

In [70]:
arr3D = np.array([[1,2,3],[4,5,6],[7,8,9]]).reshape(3, 3)
arr3D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
second_column = arr3D[:, 1]
second_column 

array([2, 5, 8])

### Q8. Create a 1D array with 10 elements and reshape it into a 2x5 matrix.

In [76]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Q9. Create two 2x2 matrices and perform matrix multiplication.

In [80]:
mat1 = np.array([[1, 2],[3, 4]])
mat2 = np.array([[5, 6],[7, 8]])
mul = mat1 * mat2
mul

array([[ 5, 12],
       [21, 32]])

### Q10. Given the array arr = np.array([5, 12, 7, 18, 3]), replace all values greater than 10 with 100.

In [83]:
arr = np.array([5, 12, 7, 18, 3])
arr[arr > 10] = 100
arr

array([  5, 100,   7, 100,   3])